/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetsRouteImport } from './routes/sets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsIndexRouteImport } from './routes/cards.index'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'

const SetsRoute = SetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sets': typeof SetsRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/': typeof CardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sets': typeof SetsRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards': typeof CardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sets': typeof SetsRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/': typeof CardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sets' | '/cards/$cardId' | '/cards/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sets' | '/cards/$cardId' | '/cards'
  id: '__root__' | '/' | '/sets' | '/cards/$cardId' | '/cards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetsRoute: typeof SetsRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sets': {
      id: '/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof SetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetsRoute: SetsRoute,
  CardsCardIdRoute: CardsCardIdRoute,
  CardsIndexRoute: CardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
